"""add_payments_and_biometrics

Revision ID: 975bd29973d9
Revises: 001_initial_schema
Create Date: 2026-06-14 22:40:06.968051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '975bd29973d9'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Bank account record unique identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user reference (intentionally no FK to allow soft-linking)'),
    sa.Column('bank_name', sa.String(length=255), nullable=False, comment='Display name of the bank (e.g. Chase, Wells Fargo)'),
    sa.Column('account_type', sa.String(length=50), nullable=False, comment='checking | savings | business'),
    sa.Column('account_mask', sa.String(length=4), nullable=False, comment='Last 4 digits of account number for display'),
    sa.Column('routing_mask', sa.String(length=4), nullable=True, comment='Last 4 digits of routing number (display only)'),
    sa.Column('account_holder_name', sa.String(length=255), nullable=True, comment='Name on the bank account'),
    sa.Column('encrypted_token', sa.String(length=1000), nullable=False, comment='Encrypted Plaid access token / Stripe bank token / internal ref'),
    sa.Column('token_provider', sa.String(length=50), nullable=False, comment='internal | plaid | stripe | manual'),
    sa.Column('external_account_id', sa.String(length=255), nullable=True, comment='Provider-side account ID (e.g. Plaid account_id)'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='Micro-deposit or instant verification passed'),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False, comment='Primary account used for payments if multiple are linked'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag'),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False, comment='ISO 4217 currency code'),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the account was linked'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='When the account was verified'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts'))
    )
    op.create_index(op.f('ix_bank_accounts_external_account_id'), 'bank_accounts', ['external_account_id'], unique=True)
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Merchant unique identifier'),
    sa.Column('business_name', sa.String(length=255), nullable=False, comment='Registered business name'),
    sa.Column('business_email', sa.String(length=320), nullable=False, comment='Business contact / API owner email'),
    sa.Column('business_category', sa.String(length=100), nullable=True, comment='e.g. retail, hospitality, healthcare, e-commerce'),
    sa.Column('website_url', sa.String(length=500), nullable=True, comment='Merchant website'),
    sa.Column('description', sa.Text(), nullable=True, comment='Short description of the business'),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True, comment='bcrypt-hashed API key for merchant-facing payment requests'),
    sa.Column('api_key_prefix', sa.String(length=12), nullable=True, comment='First 8 chars of API key for display (e.g. nf_live_ab12)'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='KYB (Know Your Business) verification passed'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-disable a merchant without deleting records'),
    sa.Column('is_sandbox', sa.Boolean(), server_default='true', nullable=False, comment='True = sandbox / test mode, False = live payments'),
    sa.Column('settlement_account', sa.String(length=255), nullable=True, comment='Encrypted bank account or settlement reference for payouts'),
    sa.Column('default_currency', sa.String(length=3), server_default='USD', nullable=False, comment='ISO 4217 currency code'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='KYB verification approval timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_index(op.f('ix_merchants_api_key_hash'), 'merchants', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_merchants_business_email'), 'merchants', ['business_email'], unique=True)
    op.create_table('fingerprint_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Fingerprint template record unique identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user reference'),
    sa.Column('template_data', sa.LargeBinary(length=2048), nullable=False, comment='Binary minutiae template in ISO/IEC 19794-2 format'),
    sa.Column('finger_position', sa.Integer(), nullable=False, comment='ISO 19794-2 finger position code (1=right_thumb, 2=right_index, ...)'),
    sa.Column('finger_position_label', sa.String(length=30), nullable=True, comment='Human-readable finger position (e.g. right_index)'),
    sa.Column('minutiae_count', sa.Integer(), nullable=True, comment='Number of minutiae points extracted'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='NIST fingerprint quality score (0–100, NFIQ2)'),
    sa.Column('ridge_density', sa.Float(), nullable=True, comment='Ridge density metric (ridges per mm) — enrollment quality indicator'),
    sa.Column('capture_device', sa.String(length=100), nullable=True, comment='Scanner model / hardware SDK used (e.g. Futronic FS80H)'),
    sa.Column('capture_dpi', sa.Integer(), nullable=True, comment='Image resolution at capture in DPI (typically 500 or 1000)'),
    sa.Column('impression_type', sa.String(length=20), nullable=False, comment='live_scan | rolled | latent'),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False, comment='Minutiae extraction algorithm version tag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Enrollment timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fingerprint_templates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fingerprint_templates'))
    )
    op.create_index(op.f('ix_fingerprint_templates_user_id'), 'fingerprint_templates', ['user_id'], unique=False)
    op.create_table('iris_embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='IrisEmbedding record unique identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user reference'),
    sa.Column('iris_code', sa.LargeBinary(length=256), nullable=False, comment='256-byte binary IrisCode from 2D Gabor phase extraction'),
    sa.Column('iris_mask', sa.LargeBinary(length=256), nullable=True, comment='256-byte occlusion mask (1=reliable, 0=occluded by eyelash/glare)'),
    sa.Column('eye_side', sa.String(length=5), nullable=False, comment='left | right'),
    sa.Column('iris_radius_px', sa.Integer(), nullable=True, comment='Detected iris radius in pixels (quality indicator)'),
    sa.Column('pupil_radius_px', sa.Integer(), nullable=True, comment='Detected pupil radius in pixels'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='Enrollment image quality score (0–100)'),
    sa.Column('usable_bits_ratio', sa.Float(), nullable=True, comment='Fraction of non-occluded bits in the IrisCode (0.0–1.0)'),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False, comment='IrisCode algorithm version tag for future re-enrollment'),
    sa.Column('source_image_path', sa.String(length=500), nullable=True, comment='Path to the source iris image (local or S3)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Enrollment timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_iris_embeddings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iris_embeddings'))
    )
    op.create_index(op.f('ix_iris_embeddings_user_id'), 'iris_embeddings', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Transaction unique identifier'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Paying user (null if biometric did not resolve to a known user)'),
    sa.Column('merchant_id', sa.UUID(), nullable=True, comment='Receiving merchant'),
    sa.Column('bank_account_id', sa.UUID(), nullable=True, comment='Source bank account used for settlement (denormalized for audit)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='Transaction amount (positive = debit from user)'),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False, comment='ISO 4217 currency code'),
    sa.Column('amount_settled', sa.Numeric(precision=18, scale=4), nullable=True, comment='Actual settled amount (may differ due to fx fees)'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='pending | authorized | settled | failed | refunded'),
    sa.Column('failure_reason', sa.String(length=255), nullable=True, comment='Human-readable failure reason if status=failed'),
    sa.Column('biometric_modality', sa.String(length=30), nullable=False, comment='face | iris | fingerprint | multi_modal'),
    sa.Column('fusion_score', sa.Float(), nullable=True, comment='Final biometric fusion score (0.0–1.0) used to authorize'),
    sa.Column('is_liveness_passed', sa.String(length=5), server_default='false', nullable=False, comment='Anti-spoofing liveness check result'),
    sa.Column('merchant_reference', sa.String(length=255), nullable=True, comment="Merchant's own order/invoice ID for reconciliation"),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable payment description'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address at time of payment (IPv4 or IPv6)'),
    sa.Column('device_id', sa.String(length=255), nullable=True, comment='Device fingerprint or terminal ID'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User agent / SDK version string'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Transaction initiation timestamp'),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True, comment='Biometric authorization completion timestamp'),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True, comment='Settlement completion timestamp'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_transactions_merchant_id_merchants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_reference'), 'transactions', ['merchant_reference'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('transaction_biometric_details',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False, comment='Parent transaction'),
    sa.Column('face_similarity_score', sa.Float(), nullable=True, comment='ArcFace cosine similarity (0–1)'),
    sa.Column('face_liveness_score', sa.Float(), nullable=True, comment='Face liveness score (0–100)'),
    sa.Column('iris_hamming_distance', sa.Float(), nullable=True, comment='Iris IrisCode Hamming Distance (0–1, lower=better)'),
    sa.Column('iris_match_score', sa.Float(), nullable=True, comment='Derived iris match confidence (0–1)'),
    sa.Column('fingerprint_match_score', sa.Float(), nullable=True, comment='Minutiae match score (0–1)'),
    sa.Column('fusion_score', sa.Float(), nullable=True, comment='Weighted fusion score (0–1)'),
    sa.Column('face_liveness_passed', sa.String(length=5), server_default='false', nullable=False),
    sa.Column('anti_spoof_passed', sa.String(length=5), server_default='false', nullable=False),
    sa.Column('blink_detected', sa.String(length=5), server_default='false', nullable=False),
    sa.Column('head_turn_detected', sa.String(length=5), server_default='false', nullable=False),
    sa.Column('face_embedding_hash', sa.String(length=64), nullable=True, comment='SHA-256 of the face embedding used'),
    sa.Column('iris_code_hash', sa.String(length=64), nullable=True, comment='SHA-256 of the IrisCode used'),
    sa.Column('fingerprint_template_hash', sa.String(length=64), nullable=True, comment='SHA-256 of the fingerprint template used'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_biometric_details_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_biometric_details'))
    )
    op.create_index(op.f('ix_transaction_biometric_details_transaction_id'), 'transaction_biometric_details', ['transaction_id'], unique=True)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.UUID(),
               comment='User who performed the action; null for automated/system actions',
               existing_comment='User who performed the action; null for system actions',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment="Machine-readable action verb, e.g. 'user.create', 'enrollment.reset'",
               existing_comment="Machine-readable action verb, e.g. 'user.create'",
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=100),
               comment="Entity/table name affected, e.g. 'users', 'face_embeddings'",
               existing_comment="Entity/table name affected, e.g. 'users'",
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_metadata_gin'), table_name='audit_logs', postgresql_using='gin')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_auth_logs_result'), table_name='auth_logs')
    op.alter_column('enrollment_logs', 'avg_quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Mean quality score for accepted images (0–100); null if none accepted',
               existing_comment='Mean quality score for accepted images (0–100)',
               existing_nullable=True)
    op.drop_index(op.f('ix_enrollment_logs_status'), table_name='enrollment_logs')
    op.alter_column('face_embeddings', 'embedding_vector',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               comment='512-dimensional ArcFace face embedding (L2-normalized)',
               existing_comment='512-dimensional ArcFace face embedding (L2-normalised)',
               existing_nullable=False)
    op.alter_column('face_embeddings', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Face image quality score at enrollment (0-100)',
               existing_comment='Face image quality score at enrollment (0–100)',
               existing_nullable=True)
    op.alter_column('face_embeddings', 'source_image_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Path to source enrollment image (local or S3 key)',
               existing_comment='Storage path of the source enrollment image',
               existing_nullable=True)
    op.drop_index(op.f('ix_face_embeddings_version'), table_name='face_embeddings')
    op.add_column('users', sa.Column('is_iris_enrolled', sa.Boolean(), server_default='false', nullable=False, comment='True once iris enrollment is complete'))
    op.add_column('users', sa.Column('is_fingerprint_enrolled', sa.Boolean(), server_default='false', nullable=False, comment='True once fingerprint enrollment is complete'))
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.alter_column('verification_logs', 'liveness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Liveness detection score (0–100; ≥ LIVENESS_THRESHOLD = live)',
               existing_comment='Liveness detection score (0–100)',
               existing_nullable=True)
    op.alter_column('verification_logs', 'anti_spoof_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Anti-spoof confidence score (0–100; higher = more genuine)',
               existing_comment='Anti-spoofing confidence score (0–100)',
               existing_nullable=True)
    op.alter_column('verification_logs', 'method',
               existing_type=sa.VARCHAR(length=100),
               comment="Pipeline / model variant used for this check, e.g. 'mediapipe_v1'",
               existing_comment="Pipeline / model variant used, e.g. 'mediapipe_v1'",
               existing_nullable=True)
    op.drop_index(op.f('ix_verification_logs_result'), table_name='verification_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_verification_logs_result'), 'verification_logs', ['result'], unique=False)
    op.alter_column('verification_logs', 'method',
               existing_type=sa.VARCHAR(length=100),
               comment="Pipeline / model variant used, e.g. 'mediapipe_v1'",
               existing_comment="Pipeline / model variant used for this check, e.g. 'mediapipe_v1'",
               existing_nullable=True)
    op.alter_column('verification_logs', 'anti_spoof_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Anti-spoofing confidence score (0–100)',
               existing_comment='Anti-spoof confidence score (0–100; higher = more genuine)',
               existing_nullable=True)
    op.alter_column('verification_logs', 'liveness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Liveness detection score (0–100)',
               existing_comment='Liveness detection score (0–100; ≥ LIVENESS_THRESHOLD = live)',
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.drop_column('users', 'is_fingerprint_enrolled')
    op.drop_column('users', 'is_iris_enrolled')
    op.create_index(op.f('ix_face_embeddings_version'), 'face_embeddings', ['embedding_version'], unique=False)
    op.alter_column('face_embeddings', 'source_image_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Storage path of the source enrollment image',
               existing_comment='Path to source enrollment image (local or S3 key)',
               existing_nullable=True)
    op.alter_column('face_embeddings', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Face image quality score at enrollment (0–100)',
               existing_comment='Face image quality score at enrollment (0-100)',
               existing_nullable=True)
    op.alter_column('face_embeddings', 'embedding_vector',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               comment='512-dimensional ArcFace face embedding (L2-normalised)',
               existing_comment='512-dimensional ArcFace face embedding (L2-normalized)',
               existing_nullable=False)
    op.create_index(op.f('ix_enrollment_logs_status'), 'enrollment_logs', ['status'], unique=False)
    op.alter_column('enrollment_logs', 'avg_quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Mean quality score for accepted images (0–100)',
               existing_comment='Mean quality score for accepted images (0–100); null if none accepted',
               existing_nullable=True)
    op.create_index(op.f('ix_auth_logs_result'), 'auth_logs', ['authentication_result'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_metadata_gin'), 'audit_logs', ['metadata'], unique=False, postgresql_using='gin')
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=100),
               comment="Entity/table name affected, e.g. 'users'",
               existing_comment="Entity/table name affected, e.g. 'users', 'face_embeddings'",
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment="Machine-readable action verb, e.g. 'user.create'",
               existing_comment="Machine-readable action verb, e.g. 'user.create', 'enrollment.reset'",
               existing_nullable=False)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.UUID(),
               comment='User who performed the action; null for system actions',
               existing_comment='User who performed the action; null for automated/system actions',
               existing_nullable=True)
    op.drop_index(op.f('ix_transaction_biometric_details_transaction_id'), table_name='transaction_biometric_details')
    op.drop_table('transaction_biometric_details')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_iris_embeddings_user_id'), table_name='iris_embeddings')
    op.drop_table('iris_embeddings')
    op.drop_index(op.f('ix_fingerprint_templates_user_id'), table_name='fingerprint_templates')
    op.drop_table('fingerprint_templates')
    op.drop_index(op.f('ix_merchants_business_email'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_api_key_hash'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_external_account_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
